// SPDX-FileCopyrightText: 2025 LunNova
//
// SPDX-License-Identifier: MIT
//! Nothing should be generated by cargo-derive-doc in this
//! file; it only uses obvious builtin derives

#![allow(dead_code, unused)]

#[derive(Debug, Clone)]
struct MyStruct {
	field: String,
}

#[derive(Debug, PartialEq)]
enum MyEnum {
	Variant1,
	Variant2(String),
}

fn main() {
	todo!()
}
